# Generated by Django 4.2.7 on 2023-12-11 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_position', models.CharField(max_length=200)),
                ('wage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('age', models.IntegerField()),
                ('years_working', models.IntegerField()),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.employees')),
            ],
        ),
    ]
